### ISSUE TITLE
documentation

### ISSUE THREAD

**Issue by dullbananas** [Pebaz/nimporter#1]
we need documentation

**Comment by dullbananas** [comment]
Also, how did you get this  any stars

**Comment by Pebaz** [comment]
I agree! I am currently working on content for the wiki pages. In regards to the Stars, I posted on the Python and Nim Subreddits so people could see my project!

**Comment by dullbananas** [comment]
check out my "dish" project

**Comment by dullbananas** [comment]
This project makes me want to learn Nim

**Comment by dullbananas** [comment]
I think i’m going to do a test to compare the speed of Cython and Nimporter.

**Comment by Pebaz** [comment]
Nice project!
Do it! I'd be interested in seeing the results. They should be comparable since Nim compiles to C and Cython is a Python to C compiler. However, since Cython makes use of interpreter calls and Nim does not, the performance may be different.

**Comment by dullbananas** [comment]
I use PythonAnywhere and I have been unable to install Nim on there because I don't have enough storage

**Comment by dullbananas** [comment]
I have now been using Repl.it instead. It kinda worked good, but Repl.it has been super buggy and there is a file that is broken. https://repl.it/@shamshung/Performance-Comparison-of-Cython-and-Nimporter

**Comment by Pebaz** [comment]
Repl.it never loads for me. It shows your project's folder structure, but the code never loads.
It may be easier to distribute your results if you create a GitHub repo with the code, run the tests locally and then post the results in the readme. Kind of like how I did [here](https://github.com/Pebaz/wrap).

**Comment by dullbananas** [comment]
Maybe I can use GitHub Actions

**Comment by Pebaz** [comment]
Does Nimporter not work on your local development machine?
If so, can you provide your machine details (OS, arch, Python version, etc.) so I can try to replicate?

**Comment by dullbananas** [comment]
I use an iPad Pro, so I use PythonAnywhere for development. It runs Ubuntu and Python 3.8. I can't install Nim on it because there's not enough storage space, and I don't want to upgrade for more storage.

**Comment by Pebaz** [comment]
I'm glad there is no issue with Nimporter! ;)
I definitely feel you though. Perhaps you could look into [AWS Workspaces](https://aws.amazon.com/workspaces/).
Also, I am marking this issue as closed since I am [actively adding documentation](https://github.com/Pebaz/nimporter/wiki).

**Comment by dullbananas** [comment]
> I definitely feel you though. Perhaps you could look into [AWS Workspaces](https://aws.amazon.com/workspaces/).

is this free?

**Comment by Pebaz** [comment]
No, but it would cost around the same per month. An alternative would be to
use AWS EC2 to spin up a T2.micro or T2.nano instance and SSH into it. It
would give you all the same features of Pythonanywhere without the hubbub
and unlimited freedom!

**Comment by dullbananas** [comment]
I have successfully been able to run a performance test. Results are here: https://github.com/dullbananas/nimporter-vs-cython/commit/ea52215fa0bde8cee2134afb5eaa48b18f538860/checks?check_suite_id=357999486

Unfortunately, Cython ran about 5 times faster.

**Comment by dullbananas** [comment]
do you have anything to say about this?
