### ISSUE TITLE
Add nimporter commands to build binary and source distributions

### ISSUE THREAD

**Issue by AngelEzquerra** [Pebaz/nimporter#11]
Even though it should not be very difficult to generate a binary or source distribution by following the nimoorter README, it would be nice if the nimporter command line tool included a command to do it for you. IMHO this would make the tool make the whole process fully “idiot proof”.

Basically it would look for a setup.py file and create it if it didn’t exist. It would check if the necessary code is there already and if not it would add it. Finally it would make the appropriate call to “python setup.py”.

**Comment by Pebaz** [comment]
This is a good idea.

I will look into it, thanks for your input! :)
