### ISSUE TITLE
setup.cfg instead of setup.py

### ISSUE THREAD

**Issue by juancarlospaco** [Pebaz/nimporter#26]
Use `setup.cfg` instead of `setup.py` on the documentation and the `setup.py` generator.

- https://gist.github.com/juancarlospaco/b91d7736281e2090fce84ed399c68972

`.cfg` can be easy to generate/parse from Nim using `parsecfg` module, builtin on Python.
:slightly_smiling_face:

**Comment by Pebaz** [comment]
Hello @juancarlospaco !

Can you explain a bit more about the advantages to this approach?

I'd be willing to consider switching to the `setup.cfg` if I knew more about how it could benefit the project.

**Comment by juancarlospaco** [comment]
It suppose to be the best practice for Python.
It is a format common to both languages.
It is a config format instead of code.

**Comment by Pebaz** [comment]
I have taken the time to look into this and although I (personally) will begin to use `setup.cfg` in future projects, I wish to leave `setup.py` as it is for now.

Thanks for introducing `setup.cfg` to me though I have not used it until today! 🙂
