### ISSUE TITLE
Release GH Action works on Mac but not Linux/Windows

### ISSUE THREAD

**Issue by Benjamin-Lee** [Pebaz/nimporter#38]
I'm a bit stumped as to what's going wrong since Windows and Linux give different errors. On Mac, it seems to be working.

[Here](https://github.com/IQTLabs/librtd/blob/99afada038718b080bb9185a449a586f17dc5d2f/.github/workflows/release.yml)'s the GH action. The parts that I modified are the installation steps in which I first install my package and then the dependencies for the CLI package. 

The errors I'm getting can be seen [here for Linux](https://github.com/IQTLabs/librtd/runs/1377822007?check_suite_focus=true) and [here for Windows](https://github.com/IQTLabs/librtd/runs/1377822020?check_suite_focus=true). Briefly, on Linux, I'm getting this:

```python
Traceback (most recent call last):
  File "<string>", line 1, in <module>
IndexError: list index out of range
```

On Windows, I'm not able to use the `python3` function:

```
python3: D:\a\_temp\ea2d772e-0efd-40be-942c-5d46b8d41f17.ps1:8
Line |
   8 |  python3 setup.py bdist_wheel
     |  ~~~~~~~
     | The term 'python3' is not recognized as the name of a cmdlet, function, script file, or operable
     | program. Check the spelling of the name, or if a path was included, verify that the path is correct
     | and try again.
```

Do you have any suggestions? I'm so happy that librtd is finally close to release!

**Comment by Pebaz** [comment]
@Benjamin-Lee thanks for reaching out!

Couple things:
* Don't use `python3` on any platform: use `python` command instead since the Python setup action sets up the right aliases and links automatically
* The index error I believe is related to the line of code that contains `"pebaz"` in the `python -c` call. This is my username which is probably why it's not working for you. Try changing it to your username and rerun

Let me know how it goes! :)

**Comment by Benjamin-Lee** [comment]
Thanks for the advice @Pebaz. Your Windows suggestion worked perfectly but Linux was a tough nut to crack. I ended up spending the day working on packaging and found a way to compile _true_ manylinux wheels for all modern Python version. To do so, I had to run the build in a Docker container provided by PyPA:

```yaml
jobs:
  build-linux:
    runs-on: ubuntu-latest
    container:
      image: quay.io/pypa/manylinux2014_x86_64
    steps:
      - uses: actions/checkout@v2
      - run: |
          curl -O https://nim-lang.org/choosenim/init.sh
          sh init.sh -y
      - name: Build and publish
        env:
          TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
        run: |
          export PATH=/github/home/.nimble/bin:$PATH
          cd $GITHUB_WORKSPACE
          choosenim 1.4.0
          nim -v
          cd librtd
          nimble install -Y
          cd ../librtd-py/librtdpy
          nimble install -Y
          cd ../
          for PYBIN in /opt/python/*/bin/; do 
            if ! test $PYBIN -ef /opt/python/cp35-cp35m/bin/; then
              "${PYBIN}/pip" install setuptools wheel twine nimporter>=1.0.2
              "${PYBIN}/pip" wheel . --no-deps -w wheelhouse/
            fi
          done
          mkdir repaired
          for whl in wheelhouse/*.whl; do
              auditwheel repair "$whl" -w repaired
          done
          /opt/python/cp39-cp39/bin/twine upload repaired/*
```

Similarly, I added Python 3.5-3.9 builds for Windows and Mac. The full build script is [here](https://github.com/IQTLabs/librtd/blob/master/.github/workflows/release.yml). Feel free to take anything from it for the example build script.

**Comment by Pebaz** [comment]
Fantastic! Glad to hear it 👏
Thank you for sharing this!

**Comment by Pebaz** [comment]
Closing due to issue being resolved! 😁
