### ISSUE TITLE
Does not work with methods

### ISSUE THREAD

**Issue by lhupfeldt** [Pebaz/nimporter#45]
```nim
import nimpy


type
  My* = ref object of RootObj
    xx: string


proc myHelp*(my: My): string {.exportpy.} =
  return "mine"

  
method mmyHelp*(my: My): string {.base,exportpy.} =
  return "mine"
```
`
ttt.nim(13, 1) Error: Expected one of {nnkProcDef, nnkIteratorDef, nnkFuncDef}, got nnkMethodDef
`

**Comment by Pebaz** [comment]
This has to do with [Nimpy](https://github.com/yglukhov/nimpy) rather than Nimporter directly. Please consult with Nimpy's documentation. Let me know if you can get this working because I'm curious myself if methods will work. My guess is that Nimpy does not support them but I could be wrong.

**Comment by lhupfeldt** [comment]
Correct, seems Nimpy does not handle types and methods. So I probably can't use it. Too bad.

**Comment by Pebaz** [comment]
Closing this for now as it seems a determination has been made.

**Comment by xyb** [comment]
@Pebaz nimpy already supports types and methods, so  we can follow up now. See https://github.com/yglukhov/nimpy/pull/210
