### ISSUE TITLE
Can you create a Discussion section for the project for easier collaboration.

### ISSUE THREAD

**Issue by SekouDiaoNlp** [Pebaz/nimporter#49]
Hi @Pebaz ,

I received your invitation to the repository, but I think it would be easier to communicate through the discussion pages.

@SekouDiaoNlp

**Comment by SekouDiaoNlp** [comment]
For my part I forked the repo and I am studying the code while having a look at the issues.

Cheers

@SekouDiaoNlp

**Comment by Pebaz** [comment]
Awesome! I will create the discussion page on GitHub soon!
