### ISSUE TITLE
how to keep so files inside __pycache__?

### ISSUE THREAD

**Issue by timotheecour4** [Pebaz/nimporter#73]
This repo manages to keep all artifacts under __pycache__; how would I place the `.so` file under `__pycache__` when using nimpy without nimporter?
eg, I'd like to run `nim c --app:lib --out:__pycache__/mymodule.so --threads:on mymodule` instead of `nim c --app:lib --out:mymodule.so --threads:on mymodule` in https://github.com/yglukhov/nimpy, but as is, placing the so inside the __pychache__ doesn't work.

Thanks, I know it's a tangential question to this repo.

**Comment by Pebaz** [comment]
Hi @timotheecour4! I think what you are looking for is `--nimcache:__pycache__`, but you might have to make sure the `__pycache__` directory is created prior to invoking the Nim compiler. I haven't had an opportunity to test but that's what Nimporter is using so I think that should work for you. 🙂 I'd be happy to help with any further questions, closing for now.
