### ISSUE TITLE
Nimporter workflow not working

### ISSUE THREAD

**Issue by thatrandomperson5** [Pebaz/nimporter#79]
Link to the broken workflow: https://github.com/thatrandomperson5/intenc/actions/runs/3772384552/jobs/6413282386
I have no idea what any of it means
The build step it broken all other parts before are fine.
**UPDATE:** The linux and macos builds are working, only the windows one is broken.

**Comment by Pebaz** [comment]
Unfortunately the pipeline results have expired. If there's an issue with Nimporter Windows support with valid usage as defined by the README let me know by reopening this issue. 👍
